### ISSUE TITLE
Bot randomly shutting down after being online for a bit

### ISSUE THREAD

**Issue by naterchrdsn** [Richardson-Media-House/Kirbi#75]
No descriptive error text, so I'm running a test bot locally in debug mode to try to find this one out

**Comment by naterchrdsn** [comment]
this must just have to do with misc errors encountered with our code

**Comment by naterchrdsn** [comment]
happened in dev, no descriptive error

**Comment by naterchrdsn** [comment]
```
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Client.emit (events.js:163:17)
    at WebSocketConnection.onError (C:\DEV\Kirbi\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:357
:17)
    at process.nextTick (C:\DEV\Kirbi\node_modules\uws\uws.js:80:19)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by naterchrdsn** [comment]
i would like to see if running the process in `forever` fixes this

**Comment by develogix** [comment]
This seems to be fixed with the latest release of Discord.JS; https://github.com/hydrabolt/discord.js/releases/tag/11.2.0

We should continue monitoring this issue though.

**Comment by naterchrdsn** [comment]
closing this for now, not seeing any more bugs
